import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.
*/
export default {
  autogeneratedSidebar: [
    {
      type: "doc",
      id: "overview",
    },

    {
      type: "category",
      label: "Getting Started",
      collapsed: false,
      items: [
        "getting-started/installation",
        "getting-started/install-editor",
        "getting-started/create-project",
        "getting-started/add-existing-project",
        "getting-started/launcher-settings",
      ],
    },
    {
      type: "category",
      label: "Guides",
      collapsed: false,
      items: [
        {
          type: "category",
          label: "Project Workflow",
          collapsed: false,
          items: [
            "guides/using-git",
            "guides/install-git",
            "guides/vscode-setup-for-godot",
            "guides/change-project-editor",
            "guides/editor-settings",
            "project-badges",
          ],
        },
        {
          type: "category",
          label: "Launcher Tips",
          collapsed: false,
          items: [
            "guides/launch-godot-project-in-windowed-mode",
            "guides/system-tray",
          ],
        },
        {
          type: "category",
          label: "Platform Specific",
          collapsed: false,
          items: [
            "guides/windows-winget",
            "guides/windows-symlink",
            "guides/linux-no-sandbox",
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Support & Community",
      collapsed: false,
      items: [
        "help-and-support",
        "community",
      ],
    },
    {
      type: "category",
      label: "Contributing",
      collapsed: false,
      items: [
        "contributing",
        "contributing/translations",
        {
          type: "link",
          label: "Roadmap",
          href: "https://github.com/orgs/godotlauncher/projects/1",
        },
      ],
    },
    {
      type: "doc",
      id: "license",
    },
  ],
};
