import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.
*/
export default {
  autogeneratedSidebar: [
    {
      type: "doc",
      id: "overview",
    },

    {
      type: "category",
      label: "Get Started",
      collapsed: false,
      items: [
        "getting-started/installation",
        "editors/install-editor",
        "projects/create-project",
        "projects/add-existing-project",
      ],
    },
    {
      type: "category",
      label: "Editors",
      collapsed: false,
      items: [
        "editors/custom-editors",
        "editors/change-project-editor",
        "editors/editor-settings",
      ],
    },
    {
      type: "category",
      label: "Projects",
      collapsed: false,
      items: [
        "projects/project-tool-toggles",
        "projects/project-settings",
        "projects/project-badges",
        "projects/launch-godot-project-in-windowed-mode",
      ],
    },
    {
      type: "category",
      label: "Integrations",
      collapsed: false,
      items: [
        "tools/using-git",
        "tools/install-git",
        "tools/vscode-setup-for-godot",
      ],
    },
    {
      type: "category",
      label: "Settings & Updates",
      collapsed: false,
      items: [
        "settings/launcher-settings",
        "settings/system-tray",
        "updates/manage-launcher-updates",
      ],
    },
    {
      type: "category",
      label: "Platform Guides",
      collapsed: false,
      items: [
        "platform/windows-winget",
        "platform/windows-symlink",
        "platform/linux-no-sandbox",
      ],
    },
    {
      type: "category",
      label: "Help & Troubleshooting",
      collapsed: false,
      items: [
        "troubleshooting",
        "support/help-and-support",
        "support/community",
      ],
    },
    {
      type: "category",
      label: "Contributing",
      collapsed: false,
      items: [
        "contributing",
        "contributing/translations",
        {
          type: "link",
          label: "Roadmap",
          href: "https://github.com/orgs/godotlauncher/projects/1",
        },
      ],
    },
    {
      type: "doc",
      id: "license",
    },
  ],
} satisfies SidebarsConfig;
